### PR TITLE
Adding export for data added to sysdata

### PR DESCRIPTION
**Pull request by dblodgett-usgs**

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
@rwdudley-usgs This should make what's going on more clear, sorry for the confusion.

**Comment by rwdudley-usgs** [comment]
No problem, @dblodgett-usgs. So I should generally be able to use the same syntax as that used with the histCounties data?

**Comment by dblodgett-usgs** [comment]
Yeah, more or less, the variable names will be different, but the subsetting method will be the same.

**Comment by rwdudley-usgs** [comment]
Ok, I have it working, but I'm not seeing all the HUCs for Maine showing up; I'm getting 10 of 21 of them. And if I search `huc08Poly` for, say, 01010001 (St. John), which is among the missing in the rendered map, it doesn't appear to be among the data. Could you confirm @dblodgett-usgs ?

**Comment by dblodgett-usgs** [comment]
@rwdudley-usgs - It looks like that huc8 isn't in the dataset... 

The reason you aren't seeing everything is that the states field is a little weird in that it uses a comma separated list of states. I think you could use grepl to subset in this case? 

screen shot 2016-06-03 at 1 54 29 pm

I selected all the ones with 'ME' in the name in a GIS and got this:

screen shot 2016-06-03 at 1 58 27 pm

**Comment by rwdudley-usgs** [comment]
Ok that helps. Yeah, I'll do a grepl.

**Pull request merged**
