### PR TITLE
parser functions + general package info

### PR DESCRIPTION
**Pull request by lindsayplatt**
Four data parsing functions:
1. `parseDumpFiles` parses the text files from the "dump"
2. `parseExport` parses export data excel files (including user-defined). Need to specify if file includes citations or not (`citations = TRUE` or `citations = FALSE` arguments)
3. `parseCompareData` parses the excel files containing two datasets
4. `parseEnteredElements` is not necessary, but had already been added. Pulls out information at the top of the file and adds as metadata to final data frame. Renames columns that occur below merged cells (`Thermoelectric` + `Hydroelectric`).

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@ldecicco-USGS build failed, maybe because it is looking for tests but there are none?

**Comment by ldecicco-USGS** [comment]
The message in travis is :+1: 

```
* checking package dependencies ... ERROR
VignetteBuilder package not declared: ‘knitr’
See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.

```

So...either take off the vignette builder line in the Description file, or add knitr to "Suggests"

Try that and see if your builds start working (?)

**Comment by ldecicco-USGS** [comment]
Also, remove the line:

```
BuildVignettes: true
```

until there's actually a vignette to build

**Comment by lindsayplatt** [comment]
@ldecicco-USGS ready to merge, unless you want to go ahead and do a review now (I know you were talking about pulling it down b/c it won't build on my computer)

**Comment by ldecicco-USGS** [comment]
Cool...I'll have a look in a bit!

**Pull request merged**
