### PR TITLE
adding huc08Poly to sysdata.rda

### PR DESCRIPTION
**Pull request by dblodgett-usgs**

### CODE REVIEW

**Comment by rwdudley-usgs** [comment]
In addition to the HUC08 polygons, I think we'll also need some built-in package data that makes use of HUC08s for the vignettes. I think `wUseSample.RData` we have right now doesn't have any HUC08 information in it.

**Comment by dblodgett-usgs** [comment]
Yeah... I don't have any right now... @jshourds-usgs can you help there?

**Comment by dblodgett-usgs** [comment]
I'm going to go ahead and merge this so it's available. Another PR to come when we add more data.

**Comment by jshourds-usgs** [comment]
There are some HUC8 data in the google drive file under "INTERNAL ONLY example data files>State Compiler" datasets under each state Idaho or Maine.  for ex, INTERNAL ONLY example data files>State Compiler>Maine>HUC-8
Does that help?

**Comment by rwdudley-usgs** [comment]
Thanks. It definitely helps as far as developing and testing the capability to do HUC choropleths, but I think we'll still need to include some HUC-related WU data in the package data for the examples, tests, and vignettes to run.

**Comment by jshourds-usgs** [comment]
Ok, I just did a pull request with a small subset of HUC8 data from Maine that were in the state compiler files.

**Pull request merged**
