### PR TITLE
Added HUC choropleth mapping capability

### PR DESCRIPTION
**Pull request by rwdudley-usgs**
Created new function `subset_huc_polygons.R` and added a new parameter to `choropleth_plot.R` called `unit.type` to know whether to fetch county polygons or huc polygons. Added a checkbox in `ui.R` to change `unit.type` between huc and county (default). I can produce huc maps with the function, but it doesn't work in Shiny yet for some reason.

### CODE REVIEW

**Comment by rwdudley-usgs** [comment]
I have a fix for `tests_subsetting.R`. I tried to amend the push but doesn;t seem to have worked.

**Comment by dblodgett-usgs** [comment]
If you did an amend you probably need to do `git push -f origin master`

**Comment by rwdudley-usgs** [comment]
Looking for some advice: I can't run a check locally before pushing because I keep getting this error:

```
* creating vignettes ... ERROR
Quitting from lines 48-55 (wateRuse.Rmd) 
Error: processing vignette 'wateRuse.Rmd' failed with diagnostics:
object 'wUseSample' not found
Execution halted object 'wUseSample' not found
```

I can't figure out how to resolve it. I have `wUseSample.RData` in my project and I've clicked on it and had it load into the global environment and it still is unrecognized. I have not edited line 48 and it has always worked in the past. Not sure why it is failing now.

**Comment by grrmartin-USGS** [comment]
I was getting that same error message after I edited the vignette text last
week, and I also have the file it says is missing.   I wonder if there
could be a 'hidden' character or something similar that it does not like.

**Comment by dblodgett-usgs** [comment]
I was able to fix it by adding a library call to the rmd file. I can PR that change if you like.

**Comment by rwdudley-usgs** [comment]
Sure. That'd be great.

**Comment by dblodgett-usgs** [comment]
It's merged. If you pull upstream and merge the change into your local repo your checks should pass.

**Pull request merged**
