### PR TITLE
vignette updates

### PR DESCRIPTION
**Pull request by rwdudley-usgs**
Added sections for all functions to vignette document.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
@grrmartin-USGS once this pull request is merged, you can edit the "vignettes/wateRuse.Rmd" file directly. You'll have to go in your git shell and type: "git pull upstream master"

**Comment by grrmartin-USGS** [comment]
Should the vignette indicate the way shiny works?  Some options in wateRuse
in RStudio work differently on shiny--for example, in Compare two years,
multiple data elements can be specified to facet plots in RStudio, but in
shiny, i see only one element can be selected to Compare two years.  (We
could describe how it works in RStudio and also how it works in shiny.)

**Comment by mamaupin-usgs** [comment]
I vote to have as much information as possible on how to run shiny and
getting plots.

On Wed, Jun 1, 2016 at 4:36 PM, grrmartin-USGS notifications@github.com
wrote:

> Should the vignette indicate the way shiny works? Some options in wateRuse
> in RStudio work differently on shiny--for example, in Compare two years,
> multiple data elements can be specified to facet plots in RStudio, but in
> shiny, i see only one element can be selected to Compare two years. (We
> could describe how it works in RStudio and also how it works in shiny.)
> 
> On Wed, Jun 1, 2016 at 5:32 PM, Laura DeCicco notifications@github.com
> wrote:
> 
> > @grrmartin-USGS https://github.com/grrmartin-USGS once this pull
> > request is merged, you can edit the "vignettes/wateRuse.Rmd" file
> > directly.
> > You'll have to go in your git shell and type: "git pull upstream master"
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/USGS-R/wateRuse/pull/106#issuecomment-223131480,
> > or mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/ARkrJSBtZhCwIbTjnJMpq6JLQqm8TnhSks5qHfqHgaJpZM4Ir_f8
> > 
> > .
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-R/wateRuse/pull/106#issuecomment-223145652, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARyLb3_WJMqu8o_DujZ5UMTfr8YekkHcks5qHglQgaJpZM4Ir_f8
> .

## 

Molly A. Maupin
Hydrologist
USGS Idaho Water Science Center
230 Collins Road
Boise, ID  83702

Office: (208) 387-1307
Fax:    (208) 387-1372

mamaupin@usgs.gov

**Comment by grrmartin-USGS** [comment]
OK I'll include notes as to how wateRuse works in shiny too.

**Pull request merged**
