### PR TITLE
Updated function descriptions and noted differences in shiny applicat…

### PR DESCRIPTION
**Pull request by grrmartin-USGS**
…ion.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
If you run the function:

```
devtools::build_vignettes()
```

It will modify the files needed for the user to view the vignette properly.

**Comment by rwdudley-usgs** [comment]
So I'm clear, `devtools::build_vignettes()` happens if you do a Build & Reload as well, right? But probably a quicker way to view updates to the vignettes to run the `devtools` command without a full Build & Reload?

**Comment by ldecicco-USGS** [comment]
It does NOT happen automatically on Build & Reload. You have to do it yourself.

**Comment by rwdudley-usgs** [comment]
Ahhh. Good to know. Thank you for clarifying.

**Comment by grrmartin-USGS** [comment]
So I need to run devtools::build_vignettes(), then run Build and Reload,
then commit and submit pull request again?

**Comment by ldecicco-USGS** [comment]
If you run `devtools::build_vignettes()` and **push** those changes, it will propagate up to this pull request. So, I think that's all you need to do

**Comment by grrmartin-USGS** [comment]
OK ran devtools::build_vignettes() then Pushed.

**Comment by ldecicco-USGS** [comment]
Sorry, you need to commit your changes first. There should be 3 files that have changes:

inst/doc/wateRuse.html
inst/doc/wateRuse.R
inst/doc/wateRuse.Rmd

then push

**Comment by grrmartin-USGS** [comment]
This moves forward to Molly @mamaupin-usgs  and Cheryl @cadieter-usgs for further vignette updates after loading.

**Comment by ldecicco-USGS** [comment]
Clearly something is not quite working right. I'll merge this, then remove the "vignettes/.build.timestamp" file, add that to the gitignore, and see why `devtools::build_vignettes()` doesn't seem to be working for you.

**Comment by ldecicco-USGS** [comment]
@grrmartin-USGS  this is what I see when I run the build_vignettes command:

image

Those 3 files I'm pushing up to my fork right now and going to do a pull request.

**Comment by grrmartin-USGS** [comment]
The packages to build vignettes seemed to download fine here.  but then it indicated an error in finding file wUseSample.  But this file is in my wateRuse package.  Not sure what's happening.

> devtools::build_vignettes()

.
.
.
The downloaded binary packages are in
    C:\Users\grmartin\AppData\Local\Temp\1\RtmpSIooGB\downloaded_packages
Building wateRuse vignettes
Quitting from lines 48-55 (wateRuse.Rmd) 
Error: processing vignette 'wateRuse.Rmd' failed with diagnostics:
object 'wUseSample' not found
...

**Comment by jshourds-usgs** [comment]
I often have to click on that file wUseSample.RData to get it to reload into my Global 
Environment.  If you go here: 

wusesample

and click on it and say yes it will load it and that might help.

**Pull request merged**
