### PR TITLE
changing dplyr methods to base R (remove piping + standard evals)

### PR DESCRIPTION
**Pull request by lindsayplatt**

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@ldecicco-USGS fyi

**Comment by ldecicco-USGS** [comment]
You might need to commit the NAMESPACE file changes too? That (I think) is why travis still says there's an error.

**Comment by lindsayplatt** [comment]
I took it out of the DESCRIPTION file and just removed it from the parser functions script. But after I build, the NAMESPACE file has not changed

**Comment by ldecicco-USGS** [comment]
You probably aren't getting Roxygen to "document on Build" then? The namespace on github has:

```
importFrom(dplyr,filter)
importFrom(dplyr,rename)
importFrom(dplyr,select)
```

Nothing you are committing takes those away.

**Comment by lindsayplatt** [comment]
I committed changes to those right before you commented that. BUT my settings somehow changed and were not configured to update roxygen when I build and reload. Should be good now

**Comment by ldecicco-USGS** [comment]
Cool!

**Pull request merged**
